version: '3.5'

services:

  postgres:
    container_name: postgres
    image: postgres:14
    environment:
      POSTGRES_USER: auth
      POSTGRES_PASSWORD: auth
      PGDATA: /data/postgres
    volumes:
      - postgres-db:/data/postgres
    ports:
      - "5432:5432"

volumes:
  postgres-db:
    driver: local
      
