version: '3.5'

services:

  # app:
  #   container_name: app
  #   image: okassov/pet-auth:v1
  #   environment:
  #     PG_USER: "auth"
  #     PG_PASSWORD: "auth"
  #     PG_URL: "postgres"
  #     PG_PORT: "5432"
  #     PG_DATABASE: "auth"
  #     PG_MAX_POOL: 1
  #     PG_CONN_ATTEMPTS: 10
  #     PG_CONN_TIMEOUT: 1
  #     JWT_KEY: "signing_key"
  #     JWT_TTL: "3600"
  #     SERVER_PORT: "8080"
  #     GIN_MODE: "debug"
  #   ports:
  #     - "8080:8080"

  postgres:
    container_name: postgres
    image: postgres:14
    environment:
      POSTGRES_USER: auth
      POSTGRES_PASSWORD: auth
      PGDATA: /data/postgres
    volumes:
      - postgres-db:/data/postgres
    ports:
      - "5432:5432"


  # Telemetry Components
  grafana:
    image: grafana/grafana:9.1.0
    container_name: grafana
    deploy:
      resources:
        limits:
          memory: 75M
    volumes:
      - ./infrastructure-test/grafana/grafana.ini:/etc/grafana/grafana.ini
      - ./infrastructure-test/grafana/provisioning/:/etc/grafana/provisioning/
    ports:
      - 3000:3000

  otelcol:
    image: otel/opentelemetry-collector-contrib:0.70.0
    container_name: otel-col
    deploy:
      resources:
        limits:
          memory: 125M
    restart: unless-stopped
    command: [ "--config=/etc/otelcol-config.yml", "--config=/etc/otelcol-config-extras.yml" ]
    volumes:
      - ./infrastructure-test/otelcollector/otelcol-config.yml:/etc/otelcol-config.yml
      - ./infrastructure-test/otelcollector/otelcol-config-extras.yml:/etc/otelcol-config-extras.yml
    ports:
      - "4317"          # OTLP over gRPC receiver
      - "4318:4318"     # OTLP over HTTP receiver
      - "9464"          # Prometheus exporter
      - "8888"          # metrics endpoint

  tempo:
    image: grafana/tempo:latest
    container_name: tempo
    command: [ "-config.file=/etc/tempo.yaml" ]
    volumes:
      - ./infrastructure-test/tempo/tempo.yaml:/etc/tempo.yaml
      - ../tempo-data:/tmp/tempo
    ports:
      - "14268"  # jaeger ingest
      - "3200"   # tempo
      - "4317"  # otlp grpc
      - "4318"  # otlp http
      - "9411"   # zipkin

volumes:
  postgres-db:
    driver: local
      
